apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.kafka.statefull.name }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.statefull.replicaCount }}
  selector:
    matchLabels:
      statefulset: {{ .Values.name }}
  template:
    metadata:
      labels:
        statefulset: {{ .Values.name }}
    spec:
      restartPolicy: {{ .Values.container.restartPolicy }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
            limits:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            requests:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}




    spec:
          envFrom:
          - configMapRef:
              name: {{ .Values.name }}-config-env

          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: {{ .Values.name }}-gluster-volume

        nodeSelector:
            name-node: {{ .Values.nodeSelector.nameNode }}

        volumes:
        - name: {{ .Values.name }}-gluster-volume
          glusterfs:
            endpoints: {{ .Values.name }}-endpoint
            path: volume1 
            readOnly: no