apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name }}
  lable:
    stateset: {{ .Values.name }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      statefulset: {{ .Values.matchLabels}}
  template:
    metadata:
      labels:
        statefulset: {{ .Values.matchLabels }}  # has to match .spec.template.metadata.labels
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
            requests:
              cpu: {{ .Values.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

        env:
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: zookeeper-0.zookeeper:2181
          - name: KAFKA_CFG_BROKER_ID
            value: ${HOSTNAME##*-}
            # value: echo $HOSTNAME | rev | cut -d'-' -f1 | rev
          - name: ALLOW_PLAINTEXT_LISTENER
            value: yes
          - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
          - name: KAFKA_CFG_LISTENERS
            value: INSIDE://:9092,OUTSIDE://:9093
          - name: KAFKA_CFG_ADVERTISED_LISTENERS
            value: INSIDE://:9092,OUTSIDE://$HOSTNAME:9093
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: INSIDE
          - name: KAFKA_CFG_AUTO_LEADER_REBALANCE_ENABLE
            value: true
        # envFrom:
        # - configMapRef:
        #     name: {{ .Values.kafka.configmap.name }}

        volumeMounts:
        - mountPath: /bitnami/kafka
          name: {{ .Values.name }}-gluster-volume

      nodeSelector:
            name-node: {{ .Values.nodeSelector.nameNode1 }}

        volumes:
        - name: {{ .Values.name }}-gluster-volume
          glusterfs:
            endpoints: {{ .Values.name }}-endpoint
            path: volume1 
            readOnly: no

  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.name }}-gluster-volume
      labels:
        statefulset: {{ .Values.kafka.matchLabels }}
    spec:
      accessModes: 
        - ReadWriteOnce
        - ReadOnlyMany
        - ReadWriteMany
      storageClassName: slow
      resources:
        requests:
          storage: 100Gi