apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-pv
  labels:
    pv: {{ .Values.name }}
spec:
  storageClassName: {{ .Values.name }}
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
  glusterfs:
    endpoints: gluster-endpoint
    path: zookeeper   # create zookeeper directory in gluster server 
    readOnly: no
    