apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pvc
  labels:
    pvc: {{ .Values.name }}
spec:
  storageClassName: {{ .Values.name }}
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
