
name:
  heketi: heketi
  glusterfs: glusterfs-cluster

name: heketi
servicetype: NodePort
replica: 1
restartPolicy: "Always"

secret:
  ssh: heketi-ssh-key-file
  admin: heketi-admin-secret


image: 
  repository: heketi/heketi
  tag: 10
  pullPolicy: IfNotPresent


resources:
  limits:
    cpu: 100m
    memory: 2048Mi
  requests:
    cpu: 100m
    memory: 128Mi